name: dtfgd
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.11.13         # PyTorch 2.4 and Diffusers 0.30 both support 3.11
  - pytorch=2.4.*=cuda*  # auto-falls back to cpu build if no CUDA
  - torchvision
  - diffusers=0.30.0
  - transformers=4.44.0
  - numpy=1.26.4         # < 2.0 to satisfy transformers
  - pillow=10.4.0
  - pytorch-lightning=2.4.0
  - tqdm=4.66.5
  - accelerate
  - matplotlib
  - scikit-image
  - pip                  # keep pip available
  - pip:
      - taichi==1.7.1    # PyPI build; conda lacks this exact version
      - lpips
